### ISSUE TITLE
【转换pdf中的图片】PDF 图片处理JPEG2000 不支持

### ISSUE THREAD

**Issue by swinghu** [Mararsh/MyBox#1600]
【转换pdf中的图片】PDF 图片处理JPEG2000 不支持

org.apache.pdfbox.filter.MissingImageReaderException: Cannot read JPEG2000 image: Java Advanced Imaging (JAI) Image I/O Tools are not installed

BaseBatchPdfController.java mara.mybox.controller.BaseBatchPdfController handleFile 134
BaseBatchController.java mara.mybox.controller.BaseBatchController handleFile 706
BaseBatchController.java mara.mybox.controller.BaseBatchController handleCurrentFile 682
BaseBatchController.java mara.mybox.controller.BaseBatchController$5 handle 588
BaseTask.java mara.mybox.fxml.BaseTask call 41

**Comment by Mararsh** [comment]
非常感谢你的提交！

目前的确不支持JPEG2000格式。
我记得当初是打算支持的，但是因为什么原因取消了。等我查清再回复。

**Comment by Mararsh** [comment]
查了下jai-imageio。按它的以下说明：jpeg2000被移出主支，因为它不兼容GPL版权。
MyBox只采用开放资源，所以就放弃支持jpeg2000了。

https://github.com/jai-imageio/jai-imageio-core

```
This project is called 'standalone' as unlike the original jai-imageio-core it has removed dependencies to jai-core packages (javax.media.jai) and JPEG 2000 (jj2000). This version also does not include the C implementations from libJIIO, meaning that this version is platform independent and fully redistributable under the 3-clause BSD license in [LICENSE.txt](https://github.com/jai-imageio/jai-imageio-core/blob/master/LICENSE.txt) (and thus is Apache and GPL compatible).

JPEG 2000 support is available as an additional module [jai-imageio-jpeg2000](https://github.com/jai-imageio/jai-imageio-jpeg2000) as it has a different (non-GPL compatible) license.
```

**Comment by swinghu** [comment]
thanks for reply , shuge 恰好有个文档图片是这个格式
