### ISSUE TITLE
Failed to launch JVM

### ISSUE THREAD

**Issue by Bandorigarupa** [Mararsh/MyBox#1903]
启动windows自包含程序包时显示Failed to launch JVM

**Comment by Mararsh** [comment]
从1月17日起一直未能访问github，今才看到。

我用最近几个版本试了，在自己的机器上可以启动。
很早以前的版本有过这样的问题：当exe的路径名包含汉字时，其无法启动。参见：https://github.com/Mararsh/MyBox/issues/218

如果你用的是最近的版本，则可能是新问题。请说明一下以下信息：
    - MyBox的版本
    - Windows的版本
    - 启动MyBox的路径

感谢支持！
