### ISSUE TITLE
Bug:多图混合时,前景图的透明背景会变成黑色..

### ISSUE THREAD

**Issue by lhalcyon** [Mararsh/MyBox#266]
如题,请问怎么解决.

**Comment by Mararsh** [comment]
多谢！抱歉没有即时看到你的问题！
今天上传的新版本5.0修正了这个bug。

**Comment by Mararsh** [comment]
这个问题的原因是：透明色是全零，在混合时如果不特别处理，则相当于基于黑色的混合。解决的办法是：遇到透明色不混合而是返回背景色，这样前景的透明就表现出来了。
我开发时太多想法要实现，所以黑盒测试不足，基本都是代码检视。所以，来自用户的bug提交是极大的帮助，多谢！

**Comment by Mararsh** [comment]
In 5.0, "PixelBlend.java"

> 
    protected int blend(int forePixel, int backPixel) {
        if (forePixel == 0) {                       // Pass transparency
            return backPixel;
        }
        foreColor = new Color(forePixel);
        backColor = new Color(backPixel);
        makeRGB();
        Color newColor = new Color(
                Math.min(Math.max(red, 0), 255),
                Math.min(Math.max(green, 0), 255),
                Math.min(Math.max(blue, 0), 255),
                Math.min(foreColor.getAlpha() + backColor.getAlpha(), 255));
        return newColor.getRGB();
    }

**Comment by Mararsh** [comment]
在5.0中，粘贴图片更为简单了：“图像处理”-“涂鸦”页签下，选择图片、或者ctrl+v从系统粘贴板取图片，同样可以选择混合模式，而且可以通过锚点来拖放大小和调整位置。
另外，前面版本里，混合模式中有两个模式的计算公式写错了。。。这次发现修正了。

**Comment by Mararsh** [comment]
我把这个bug关闭了。
如果问题仍存在，请帮助重新打开此问题，谢谢！

**Comment by lhalcyon** [comment]
不好意思,才看到回复.  了解了. 我这边是直接用ImageCombine改了下坐标解决的 = = .
