### ISSUE TITLE
打包后部分电脑运行报错,找不到mara.xx.MyBox类

### ISSUE THREAD

**Issue by lhalcyon** [Mararsh/MyBox#296]
不好意思,还是遇到打包跑不起来的问题. 
现在打的exe包,在没有装jdk的部分电脑上可以跑,部分电脑上报找不到主类(MyBox)的错误 ,  请问是什么问题. 

项目我改成了maven项目, 之前用的[maven-javafx-plugin](https://github.com/javafx-maven-plugin/javafx-maven-plugin) 直接打native包, 后面改用其打jar包,然后用作者的帮助文档上的方法打exe包 .   请求帮助 :(

**Comment by lhalcyon** [comment]
呃.在另外一个 Repo 中找到了解决办法.  是因为打的exe包目录路径中有中文导致的.   具体[Issue](https://github.com/javafx-maven-plugin/javafx-maven-plugin/issues/372)

**Comment by Mararsh** [comment]
是的，我也碰到这个问题，所以不得不在文档中写明这个限制：exe必须在纯英文路径下运行。
jar可以在中文路径下执行。就是exe不能在中文路径下启动。

**Comment by Mararsh** [comment]
我刚验证了下，打包可以在任何目录下，不会有错。只有启动exe受到这个限制。
希望JDK早点解决这个问题
