### ISSUE TITLE
圖片轉化時，文件夾的Recursion問題

### ISSUE THREAD

**Issue by beijingjazzpanda** [Mararsh/MyBox#772]
假設源文件設置爲 newFolder/
目標文件設置為     newFolder/result/
點擊開始之後，程序會recursively在newFolder/result/下不斷生成/result文件夾。

P.S. 這個工具太有用了，UI體驗非常棒，超級喜歡，謝謝作者的無私分享，感恩！

**Comment by Mararsh** [comment]
感谢反馈！
这个问题以前发现过，还专门提供了工具“文件”-“删除无限循环目录”（系统文件管理器没法删除），在版本v6.1里：
https://github.com/Mararsh/MyBox/issues/549

我检查一下，看看现在的版本有没有这个问题。稍后更新。

**Comment by Mararsh** [comment]
#549

**Comment by Mararsh** [comment]
我刚试了一下最近的版本v6.3.4，没有复现。
我注意到你的示例是unix目录格式，能不能请你帮我确认一下问题出现的版本和操作系统，多谢啦！

再次感谢鼓励！这个工具能有用，就是我最高兴的事了。
可惜的是这个工具没有经过足够的测试，总是冒出来新问题老问题，我在花时间写新代码和补老代码中迷茫。。。。

**Comment by Mararsh** [comment]
如果无限循环目录已经在你的电脑上产生，请试着用MyBox功能“文件”-“删除嵌套目录”来删除它。操作系统可能不能正常删除这样的目录。
抱歉bug造成的麻烦！

**Comment by Mararsh** [comment]
问题重现了。。。
版本6.3.5将尽快发布修补这个问题

**Comment by beijingjazzpanda** [comment]
OS：windows 10 
桌面上創建Desktop/New folder，
之後在Desktop/New folder中創建Desktop/New folder/New folder，作爲source folder。
tartget folder則設為Desktop/New folder/New folder (2)。
開始之後，就出現問題了。

**Comment by beijingjazzpanda** [comment]
> 我刚试了一下最近的版本v6.3.4，没有复现。
> 我注意到你的示例是unix目录格式，能不能请你帮我确认一下问题出现的版本和操作系统，多谢啦！
> 
> 再次感谢鼓励！这个工具能有用，就是我最高兴的事了。
> 可惜的是这个工具没有经过足够的测试，总是冒出来新问题老问题，我在花时间写新代码和补老代码中迷茫。。。。

沒關係的，只要是代碼，就一定會有問題，沒人能做到完美，事情的成敗看緣分，盡心盡力就是圓滿。將所有問題排序，一切按需，優先修改或添加最需要的那些，足矣，不要勉强哦！能夠在需要幫助的時候遇到這個工具，已經十分感恩了！加油！

**Comment by Mararsh** [comment]
Fixed in v6.3.5
